### ISSUE TITLE
DVC already has a completion script for Zsh

### ISSUE THREAD

**Issue by mroutis** [CaveSven/zsh_completion_dvc#1]
Hey, @CaveSven !

DVC is maintaining a completion script for Zsh, you might want to take a look or even contribute to it!

https://github.com/iterative/dvc/blob/master/scripts/completion/dvc.zsh

**Comment by CaveSven** [comment]
This is great, thanks for the hint, @mroutis

**Comment by mroutis** [comment]
Sure, @CaveSven :)
